"""
Shared Pydantic schemas for the Fashion Retrieval System.

These models are the single source of truth for data structures used
across indexing, retrieval, VLM prompting, and Qdrant payloads.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Garment-level attributes
# ---------------------------------------------------------------------------


class Garment(BaseModel):
    """Attributes for a single detected garment in an image."""

    category: Optional[str] = None
    """High-level garment type, e.g. 'top', 'bottom', 'dress', 'outerwear', 'footwear', 'accessory'."""

    subcategory: Optional[str] = None
    """Specific item type, e.g. 'crew-neck t-shirt', 'slim-fit jeans', 'maxi dress'."""

    color: Optional[str] = None
    """Dominant color(s), e.g. 'navy blue', 'black and white striped'."""

    pattern: Optional[str] = None
    """Surface pattern, e.g. 'solid', 'floral', 'plaid', 'animal print'."""

    material: Optional[str] = None
    """Fabric / material, e.g. 'cotton', 'denim', 'silk', 'leather'."""

    fit: Optional[str] = None
    """Silhouette / fit, e.g. 'slim', 'relaxed', 'oversized', 'fitted'."""

    style: Optional[str] = None
    """Fashion style, e.g. 'casual', 'streetwear', 'formal', 'bohemian'."""

    occasion: Optional[str] = None
    """Intended occasion, e.g. 'everyday', 'workwear', 'party', 'beach'."""


# ---------------------------------------------------------------------------
# Scene and person context
# ---------------------------------------------------------------------------


class SceneInfo(BaseModel):
    """Scene-level context extracted from the image."""

    location: Optional[str] = None
    """Setting, e.g. 'indoors', 'outdoors', 'studio', 'urban street'."""

    environment: Optional[str] = None
    """Broader environment, e.g. 'beach', 'forest', 'city', 'office'."""

    activity: Optional[str] = None
    """Activity being performed, e.g. 'walking', 'posing', 'sitting'."""


class PersonInfo(BaseModel):
    """Person-level attributes extracted from the image."""

    gender: Optional[str] = None
    """Perceived gender presentation, e.g. 'woman', 'man', 'unisex'."""

    num_people: Optional[int] = None
    """Number of people visible in the image."""


# ---------------------------------------------------------------------------
# Top-level metadata container
# ---------------------------------------------------------------------------


class FashionMetadata(BaseModel):
    """Structured metadata for a fashion image.

    Used both as the VLM output during indexing and as the parsed query
    representation during online retrieval.
    """

    garments: list[Garment] = Field(default_factory=list)
    """List of garments detected in the image, one entry per distinct garment."""

    scene: SceneInfo = Field(default_factory=SceneInfo)
    """Scene-level contextual information."""

    person: PersonInfo = Field(default_factory=PersonInfo)
    """Person-level attributes."""


# ---------------------------------------------------------------------------
# Qdrant payload / index record
# ---------------------------------------------------------------------------


class IndexedImage(BaseModel):
    """Full record stored in Qdrant for a single indexed image.

    ``fashionclip_embedding`` and ``caption_embedding`` are stored as
    named vectors; everything else lives in the payload.
    """

    image_id: str
    """Stable unique identifier derived from the image path (SHA-256 prefix)."""

    image_path: str
    """Absolute or dataset-relative path to the original image file."""

    caption: str
    """Free-text natural language description generated by the VLM."""

    metadata: FashionMetadata
    """Structured fashion attributes extracted by the VLM."""

    fashionclip_embedding: list[float]
    """FashionCLIP image embedding (dim=512, L2-normalised)."""

    caption_embedding: list[float]
    """BGE caption embedding (dim=768, L2-normalised)."""


# ---------------------------------------------------------------------------
# Retrieval output
# ---------------------------------------------------------------------------


class RetrievalResult(BaseModel):
    """Single result returned by the retrieval pipeline."""

    image_id: str
    image_path: str
    caption: str
    metadata: FashionMetadata
    score: float = 0.0
    """Final relevance score (higher is better). Set by the reranker."""
